---
title: "On China's Rising Power"
author: "Muhammet Özkaraca"
date: 2017-08-31T21:13:14-05:00
categories: ["Previous-OpEds"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


Amerikan ve Dünya basının bu aralar gözü kulağı Başkan Trump’ın 12 günlük Asya
ziyaretine çevrilmiş durumda. Gündemin yoğunluğu, başta Kore Yarımada’sında değişen
dengeler olmak üzere, bir yana dursun bu ziyaret aslında bir çok önemli tarihi detayı da
içinde barındıran bir seyahat. Örneğin, bu ziyaretle beraber George H. W. Bush’tan sonra,
yaklaşık olarak 25 yıl, ilk defa bu kadar uzun bir devlet gezisinde Amerikan halkı ve çıkarları “Başkan” protokolünde temsil edilecek. Öte yandan bu gezinin diğer bir çarpıcı özelliği ise Başkan Trump’ın Beyaz Saray’a gelişinden itibaren en uzun yurtdışı gezisi olması. Dünya liderleriyle arasını geçmişte iyi tutmayı pek de başaramamış olan Trump, Asya kıtasının 5 önemli ülkesi, Japonya, Güney Kore, Çin, Vietnam ve Filipinler’i ziyaret edecek. Başkan Trump’ın bu gezideki en önemli durağı ise tartışmasız olarak Çin.


Ekonomisi, kültürü, insan gücü… Tüm bunlar ve daha fazlası sebebiyle aslında Çin bu
önemi hatta dahasını hak eden bir ülke. Fakat tüm bu nedenler arasında, bazılarına göre,
sadece ekonomi önem arz ediyor ve Çin’in sahip olduğu soft power başta olmak üzere diğer
güçlü tarafları genellikle görmezden geliniyor. Bu yazımda Çin’in tüm bu başarılarının sadece ekonomik yönden anlaşılmasının çok vahim bir hata olduğunu, Çin’in tüm bunların ötesinde Soğuk Savaş’tan itibaren daha da Batılılaşmış olan dünya düzenine aslında nasıl da büyük bir tehdit sunduğunu ele almaya çalışacağım.

20. Yy. dan itibaren gelişen Dünya düzenine baktığımız zaman şunu görürüz ki
özellikle 1991 yılında Sovyetlerin dağılmasıyla birlikte az gelişmiş ya da gelişmekte olan
toplumların refaha ulaşması için tek yol liberal ekonomi politikalarını benimsemek ve bu
bağlamda kendi iktisadi programlarını düzenlemek olmuştur. Diğer bir ifadeyle 1960’lar da az gelişmiş ya da gelişmekte olan bir toplumun kendini geliştirip müreffeh bir yaşama
ulaşabilmesi için önünde 2 seçenek bulunmaktaydı. Ya Batı bloğu olan başını ABD,
İngiltere’nin çektiği daha çok serbest piyasa ekonomisine bağlı bulunan bu grubun ekonomi
politikalarını takip edecek ya da bu bloktan kendini demir bir perdeyle ayırmış başını Sovyet Rusya’nın çektiği Komünist bloğa katılıp modernleşmesini tamamlayıp ekonomisini
büyütebilecekti. İki kutuplu bu dünya düzeninde milletlerin önünde bulunan 2 seçenekten
bir olan Komünist blok Sovyetlerin dağılmasıyla başarısızlığa ulaşmış ve aslında müreffeh bir yaşam için pek de iyi bir yol olmadığı anlaşılmıştı. Yeni milenyumun arifesinde gerçekleşen bu olay Batı değerlerinin kesin bir zaferi gibi görünse de yaşadığımız dönem aslında bu yanılgının ne kadar ne çarpıcı boyutlara ulaştığını başta Çin olmak üzere büyüyen Asya ekonomileriyle bizlere kanıtlıyor.

Ucuz iş gücü, düşük vergiler, devletin yabancı sermayeye tanımış olduğu büyük ve
geniş olanaklar Çin’in bu denli büyümesinin nedenlerinden sadece birkaçı. Ama tüm bunlar
arasında asıl dikkat edilmesi gereken nokta iktisadi gücünün haricinde ülkenin Dünya
düzeninde gittikçe artan etkisi ve beraberinde getirdiği karar almaya mercilerindeki
değişiklikler. Bunun son çarpıcı örneğini Dünya Çin’in kendisinden binlerce kilometre uzaklıktaki Suriye ile ilgili olan Birleşmiş Milletler ‘in uluslararası askeri müdahale kararına verdiği vetoyla gördü. Kendisinden bunca uzaklıktaki bir ülkeye ayrıca da ticari ve stratejik ilişkileri yok denecek kadar az olmasına rağmen Çin bölgenin kaderini derinden etkileyecek bir karara imza attı. Tüm bunlara ek olarak yeni milenyumun yeni süper gücünün Dünya’yı ilerleyen zamanlarda kültürel olarak da etkilemesi de aslında bizi bekleyen konulardan biri. Gittikçe tek tipleşen Dünya düzeninde daha çok Çin kültürünün, mutfağının, geleneklerinin hatta belki de geleneksel Çin takviminin yer alması işten bile değil.



