---
title: "Interview with Turkish writer, journalist and academic Tanıl Bora on his latest book and history of Turkish politics"
author: "Muhammet Özkaraca"
date: 2018-01-26T21:13:14-05:00
categories: ["Previous-OpEds"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

*2017’den 2018’e kalan ender güzel şeylerden biriydi Tanıl Bora ile röportaj fikri benim için. Bugüne kadar pek çok kitabı, makalesi yayımlanmış olan Tanıl Hoca ile tanışmak, günlük hayatını nasıl geçirdiğini, geçmişteki olaylara hangi perspektiflerden nasıl yorumlar getirdiğini öğrenmek ve tabi ki uzun yıllar boyunca her siyasi tarihçinin masasında bir yer kaplaması kuvvetle muhtemel olan son kitabı Cereyanlar’ı konuşmak… Tüm bunları yaparken Tanıl Hoca o kadar içten ve anlayışlı davrandı ki biz de zamanın nasıl geçtiğini anlamadık ve ortaya upuzun ama bir o kadar da öğretici bir söyleşi çıkıverdi. Umarım söyleşinin sonunda siz de aynı düşünceleri paylaşırsınız. Keyif almanız dileği ile.*

> Bir gününüz nasıl geçer?

Benim için haftanın iki tür günü var. Pazartesi ve Cuma büroda çalışırım. Genellikle görüşmelerimi, buluşmalarımı bu zamanlarda yapıyorum. Salı, Çarşamba, Perşembe günlerinde evde yoğun çalışıyorum. Bizim işimizde, hem dergi hem yayınevi, çok fazla yazışma işi var. Çok fazla insana cevap vermek, inceleme sonucu aktarmak, yazı istemek… Bunla ilgili yazışmalar gerekiyor. Toplansa sanırım 2 saatten az tutmayan bir yazışma işi var her gün yapmam gereken. Bunun haricinde her gün bir saat çeviriye ayırıyorum. İki üç saat kadar yazmaya ya da yazmaya hazırlandığım çalışmalara vakit ayırıyorum. Ayrıca redaksiyonla uğraşıyorum. Ortalamayı söylüyorum elbette. Hafta sonlarında çalışmamaya ya da daha az çalışmaya çalışırım.

>Şu anda üstünde çalıştığınız projeleriniz nelerdir?

Şu anda kısa vadeli olarak, Birikim‘in internet sitesinde yazdığım, günlük siyasette sıkça tekrarlanan, tüketilen cari siyasi kavramlarla ilgili yazılar vardı. Onları derleyip bir kitap yapmaya kalkıştım. Zamanın Kelimeleri adıyla çıkacak. Orta vadeli olarak Devlet, Ocak, Dergah ve Devlet ve Kuzgun isminde, Kemal Can ile birlikte yazdığımız, MHP’yi inceleyen iki kitap vardı. Şimdi onun üçüncüsüne, 2000’lerde MHP’yi ele alan bir kitaba başladık. Isınma evresindeyiz. 1-1,5 yıl sürecek bir çalışma o. Uzun vadede de bir Hasan Ali Yücel monografisi üzerine çalışıyorum. O daha uzun, birkaç yıl sürecek bir çalışma. Bununla ilgili de yavaş yavaş, damla damla çalışıyorum.

Çeviri olarak da bitirdiğim bir iki şey var. Thomas Bauer isimli bir Şarkiyatçının İslam tarihinde müphemiyet kavramı ekseninde inceleyen bir eserinin çevirisiyle uğraşıyorum. Görülebilir vadedeki çalışma planım bu.

> Düzenli olarak yaptığınız hobileriniz var mı?

Maça giderim, yemek yapmayı severim. Ayrıca arkadaşlarımı görmeyi onlarla hasbihal yapmayı severim. Haftada iki gün uzun yüzerim. Bunların dışında.. genel olarak okuma yazmayı severim.

> Peki Cereyanlar’a gelelim. Cereyanlar kaç senelik bir çalışmanın ürünü?

Yazma süreci beş yıla yayıldı. Zaten aşağı yukarı 20-25 yaşından itibaren hep genel olarak siyasi ideolojilerle ilgilendim. İlkin daha çok sağ ideolojilerle, özellikle MHP ve milliyetçilikle ilgilenerek başladım. Bu ilgim sonra diğer ideolojilere de yayıldı. Bu konuda derli toplu, kaynak işlevi görecek bir iş yapayım diye bir niyeti yaklaşık on on beş yıldır kafamda gezdiriyordum. Ama somut olarak yazma işi, 5 yıl aldı.

> Sizce Kitabın eksik kaldığı yanları var mı? Varsa neler?

Var, çok var. Hatta onla ilgili de şöyle bir tereddüt geçirdim. Sonradan düşündüklerimle, okuduklarımla, eksik ve güdük olduğunu fark ettiğim çok yer var. Bunlarla ilgili ciddi bir tamirata girişmeyi, bazılarına eklemeler yapmayı, bazılarını yeniden ele almayı düşündüm. Ama başta İlker (Aytürk) ve Aksu olmak üzere, yargısına güvendiğim birçok arkadaşım beni şuna ikna etti: bu kadar kapsamlı bir kitabın çıkmasından 1 yıl gibi kısa bir süre sonra baştan oturup onda çok büyük değişiklikler yapmak ayıp olur. Böyle kapsamlı bir revizyon, ancak belirli bir zaman geçtikten sonra yapılabilir. Buna ikna oldum.

Bu tür bir kitap zaten insanı hep tereddütte tutar. Bu konuların uzmanı, meraklısı için ister istemez biraz yüzeysel olduğunu biliyorum, ondan ötürü biraz mahcubiyet duyuyorum. Ama bir yandan da herkes o kadar derinden ilgilenmek zorunda değil. Bu konulara ilk girenler için paranomik bir bakış sunması bakımından işe yarar diye umuyorum, o beni rahatlatıyor.

> Genellikle Türk siyasetinde çokça tartışılan bir konudur, Teori pratiğe döküldüğünde yeterli etkiyi oluşturmaz denir. Siz bu düşünceye katılıyor musunuz?

Biliyorsunuz çok elverişli bir praksis kavramı var bununla ilgili Gramsci’nin  geliştirdiği. Praksis teoriyle yoğurulan pratik anlamında kullanılır. Ya da diğer bir ifadeyle teoriyle etkileşim içindeki pratik… Aradığımız şey aslında o. Teoriyi sadece uzak bir ilham kaynağı olarak almak değil, bir fikri sürekli sınayarak kaynak olarak sürdürülebilir kılmak. Teori ile pratik arasında, iki düzlemi de birbirine hürmet ettiği, birbirinin hakkını tanıdığı bir etkileşim. Ama tabii bunu istemek arzulamak başka, gerçekten uygulamak başkadır. Türkiye’de de bu anlamda bir praksis sorunu var ama sadece Türkiye’de mi var bu? Bu bütün dünyada bir sorun, hem sağ için hem sol için. Ama tabii sol için daha büyük bir sorun, çünkü sol teoriyi, teorik tutarlılığı çok önemser. O nedenle solda bence teoriyle pratik arasındaki ilişki daha can yakıcı, daha heyecanla ve tutkuyla tartışılan bir konudur. Sağda bence bu konu o kadar sorun değildir çünkü sağ fıtraten pragmatisttir.. Şunu da ekleyeyim, pragmatizm başlıbaşına “kötü” bir şey değil, aslında belki “oportünist” demek daha doğru olacak!

> Özellikle 19. Yy. sonlarıyla 20. Yy başlarında pek çok Turancılık, Milliyetçilik idealini savunan düşünür mevcut, Ziya Gökalp, Yusuf Akçura, Emin Bülend gibi. Fakat bu zenginliği 1960’lardan sonra pek göremiyoruz. Sizce bunun nedenleri nelerdir?

Peki, şunu sorayım size. Almanya’yı alın mesela, en geniş anlamıyla sosyalist düşüncede, -içine Sosyal Demokrasi’yi de katarak-, etkili bir düşünür en son ne zaman çıktı? Demek istediğim, bu Türkiye’ye özgü bir durum değil. Bunun bence şöyle bir sosyolojik temeli de var, 19. Yy ya da 20. Yy ilk yarısına baktığımız zaman tahsilli zümreler hayli dardır. Okur yazarlar dediğimiz insanların önemli bir bölümü zaten birbirlerini tanıyorlar, en azından çok küçük bir daire içinde olup bitiyor her şey. Dolayısıyla aydın dediğimiz, yazar çizer dediğimiz insanlar seçkinler ve azlar. Bugün okuryazarlık hem geniş anlamıyla hem dar anlamıyla acayip yaygınlaşmış, kitleselleşmiş durumda. Kimsenin o zaman olduğu kadar böyle pırıl pırıl parlamamasında biraz bunun da payı yok mudur?. Ya da parlasa bile popüler kültür içinde bir süre parlar ve popüler bir figüre dönüşür. Eskisi kadar etkili bir düşünür figürü çıkmaması, bu sebepten ötürü de daha zor. Ama tabii mesele bundan ibaret değil. 19. Yy 20 yy. dönümü, çok büyük ve iyimser bir dönüşümün zamanı. Dünyanın iyiye doğru değişmekte olduğu fikrinin her cenahta insanlığı sardığı bir zaman. Bugün öyle bir zamanda değiliz. Bugün daha karamsar ve ümitsiz bir ruh hali hakim. Geleceğin ne getireceğine dair söz söyleyenler var ama çok ikna edici, gerçekten devrimci bir fikir ile de henüz karşı karşıya değiliz. Bunu ipuçları var ama bu çağın sözü henüz söylenmedi. Belki de bildiğimiz alıştığımız gibi söylenmeyecek. Belki daha kolektif bir aklın ürünü olarak çıkacak. Kısacası çağla ve dönemli bir ilgisi var bu konuştuğumuz konunun.

İkincil olarak şunla da ilgisi olabilir: o dönemlerin milliyetçilik akımı bir aydınlar hareketiydi. Fikre kitaba çok daha fazla önem veriyordu. MHP’den itibaren artık daha ziyade hareket haline dönüştü. Daha ziyade taban dinamiğiyle meşgul, aksiyona yönelmiş bir hareket. İstiyorsanız buna şunu da katın, genel olarak fikre ve düşünceye verilen önemin zaten azaldığı bir dönemdeyiz. Entel lafının bir hakaret ve küçümseme lafı olarak yaygınlaşması da bunun bir alametidir. Globalden yerele böyle bir şema çizebiliyorum.

> Erken Cumhuriyet dönemindeki Kemalizm ve Milliyetçilik arasında olan ilişkiyi biraz açar mısınız?

Farklı Kemalizm yorumlamalarının, okumalarının söz konusu olduğunu unutmamalıyız. Buna rağmen şunu söyleyebiliriz ki Kemalizm ve Milliyetçilik arasındaki eklemlenme hala çok güçlü. Bugün farklı Kemalist söylemleri arasında ayrım yapabiliriz ama çoğu milliyetçidir kendince. Erken Cumhuriyet döneminde bu iki ideolojinin birbiriyle tam olarak örtüşüyor gibi gözükmesi bizi aldatmamalı. O zaman da, Kemalizm dışı milliyetçilikler de vardı. Buna karşılık, Kemalizm içinde de, çok güçlü olmamakla birlikte, Kemalizm’in tamamen milliyetçiliğe indirgenmesinden rahatsız olan yorumlar vardı. Tek parti atmosferinin basıncı altında Kemalizm hep bir topak gibi duruyordu ama içinde ayrışmalar vardı.

> 1915-23 arasındaki Milli Kin duygusunun 1923’ten sonra zamanla Batılılaşma ‘ya doğru evirildiğini görüyoruz. Bu durumun nedenler nelerdir?

Bu yorum genel olarak doğru fakat kin saikının milliyetçiliğinin malzemesi olmaktan tamamen çıktığı anlamında da anlaşılmamalı. Batı ile ilişki, Türkiye’deki siyasal düşüncenin tamamını, bütün akımları anlamak açısından bence çok önemli bir unsur. Batı ile olan ilişkileri genelde bir hınç-haset gerilimi ekseninde tanımlamak doğru olur. Bir yandan Batı’ya meydan okumak, batının kibrine ve kuvvetine kinle bakmak, onu bir tehdit olarak algılamak… bir yandan da çok güçlü bir imrenme ve öykünme. Bu ikisi arasındaki gerilim Türkiye’deki bütün siyasal düşünce tarihinin belki de en güçlü zembereğidir. Bu bir türlü boşalmayan bir zemberek. Tabii konjonktüre göre gevşeyebiliyor.

Milli Kin de Türk milliyetçiliğine özgün bir şey değil. Milliyetçilik eninde sonunda biliyorsunuz çok güçlü bir kolektif “Biz” duygusu kurar ve her “Biz” algısı bir Öteki algısıyla beraber kurulur. O Öteki’nden kendinizi ayırt eder, ona gıcık olmaktan nefret etmeye, kinlenmeye giden yolda onunla ilgili olumsuz duygular üretirsiniz. Milliyetçilik bunu yeniden üretir. En kibar, en yumuşak milliyetçilik dahi bunu yapar. Tehdit algısı yükseldiği oranda ve hele millet inşa etme sürecinin aciliyeti içerisinde tabii ki kin kabarır – kabartılır. Bunu basitçe doğal bir duygu olarak düşünmemek lazım. Stratejik olarak da kurulan ve kurgulanan bir duygu bu.

> Erken Cumhuriyet Döneminde oluşturulan Türk tanımı toplumda bir karşılık bulabildi mi? Bu tanım insanları ikna etmesi açısından başarılı mıydı?

Burada farklı milliyetçilik tanımları rekabet halinde. Yine Türk milliyetçiliğine özgü olmayan bir şeyden söz ediyoruz: her milliyetçilik, iki farklı millet anlayışı arasında salınır. Birincisi tamamen siyasi bir vatandaşlık tanımına dayanan bir millet tanımı. Anayasal düzene bağlı olarak bu memlekette yaşayan, vatandaş olan herkes bu milletin bir ferdidir, buna göre. Dine, ırka, renge bakmaksızın. Buna Fransız ekolü milliyetçilik tanımı da denir, malum. Bir de “özcü” denen, daha çok Alman geleneğine bağlanan millet tanımı vardır. Orada, ırk olabilir, renk olabilir, din olabilir ya da bunların bir bileşkesi olabilir, doğuştan gelen ve belirli bir üstünlük atfedilen bir “öz” söz konusudur. Her milliyetçilik tanımı bu iki anlayış arasında konjonktüre göre salınır. Daha güvenli, daha sakin zamanlarda vatandaşlık temelli anlayış öne çıkarken, tehdit algılarının yükseldiği ajite dönemlerde “özcü” anlayış güç kazanır. Elbette genelleme yapıyor, şematik bir çerçeve çiziyorum. Türkiye’de hep böyle bir gerilim oldu. Tek parti döneminde de olan buydu. Vatandaşlık esası dışında bir millilik ölçüsü gözetmeyen tutumun görece daha demokratik ve özgürlükçü olduğunu düşünüyorum. Ama şunu da unutmamak lazım ki milliyetçilik hükmünü yürütürken hiçbir zaman o kadar steril olmaz.

> Kitapta bahsettiğiniz Müspet Milliyetçilik kavramını açar mısınız?

Demirel ve Özal’ın iktidarlarının müreffeh ve rahat dönemlerinde zaman zaman milliyetçiliğin bu şeklini örneklediklerini Karikatürize ederek özetleyeyim: “Geçmişte ecdadımız şunları yaptılar diyerek övünmenin bir anlamı yok, bugün bu milleti refah içinde yaşatabiliyor muyuz? Herkese refah götürebiliyor muyuz? Önemli olan budur” gibi bir söylemle. Milliyetçi hamaseti, “dünya markası yaratmak”, “dünyayla rekabet edebilecek ürünler, değerler yaratmak” gibi bir teraziye taşıyarak… Tekrarlayayım, bu, işler rahat ve yolundayken geçerlilik kazabilen bir söylem. Bunu daha tutarlı bir şekilde savunanlar da olabiliyor; ama azınlıktır.

> Türkiye’de genellikle merkez sağ partilerin iktidara geldiği bir ülke. Buradan yola çıkarak toplumun Muhafazakar-Sağ ağırlıklı olduğunu söyleyebilir miyiz?

Bir ülkenin toplumunu toptan “sağ” diye tanımlamakta daha ihtiyatlı olmalı. Fakat siyasi yöneliminde baskın bir Sağcılık olduğunu gönül rahatlığı ile söyleyebiliriz. Şu da var ki pek çok Sağcı, Sağcı terimini benimsemez. Örneğin İslamcılar kendini Sağcı olarak görmez. Onlar kendilerini bu Sağ/ Sol ikileminin üstünde görmek isterler. Solu Sol olarak tanımlamada beis görmezler ama kendilerini Sağcı değil de başka bir şeyle, “yerli” mesela, tanımlamak isterler. Bana sorarsanız, Sol/Sağ, her zaman anlamlı ve işlevsel bir şemadır.

> Bu bağlamda İdris Küçükömer’in “Türkiye’de Sol Sağdır, Sağ Soldur” sözünü nasıl yorumlarsınız?

İdris Küçükömer genellikle öyle özetlenir ama söylediği şey bence biraz daha karmaşık, daha incelikli. Şunu diyor: Türkiye’de sınıfsal ve sosyal olarak Sol’da konumlandıracağımız kitleleri Sağ siyasetler temsil ediyor. Sınıfsal ve sosyal olarak aslında Sağ’da konumlanması gereken kesimleri ise Sol temsil ediyor. O, siyasi temsiliyet ilişkisinde bir çarpıklık olduğunu anlatmaya çalışıyor. Yoksa, solcuların ve soldakilerin aslında sağcı olduğunu, -ve tersi- söylemiyor. Bu önemli bir nüanstır ve zamanında da olumlu anlamda bir provokasyondur. Beri yandan mesela 70’li yıllarda bu temsiliyet ilişkisinin öyle olmaktan hızla çıktığını biliyoruz. İşçi sınıfı büyük çoğunlukta CHP’ye oy veriyordu. Dolayısıyla bu şemanın hem bahsettiğim inceliğini gözden kaçırmamalı, hem de sabit ve tıpa tıp doğru bir şema olarak kabul etmemeli.

> Globalizm ile birlikte Milliyetçiliğin etkisinin azalmaya başladığı sanılmıştı ki Popülizm ve onun etkisindeki yükselen Sağ ile birlikte bunun böyle olmadığı anlaşıldı. Bu durumun sebepleri nelerdir?

Aslında bu durum sadece yükselen Popülizm ile alakalı değil. Bu bahsettiğiniz durum insanların yüzüne nasıl çarptı? Tam da “bütün dünya tek bir ülke gibi oldu, ulus devlet sınırları anlamını yitiriyor” denirken, büyük bir milliyetçi patlamayla Yugoslavya iç savaşı kopuverdi. Kimileri dedi ki, bu eski dünyanın son can çekişmesi, anakronik bir şey, saçma. Ama ilerleyen zamanlarda bunun böyle olmadığı ortaya çıktı. Globalleşme evet bir yandan bütün dünyayı hemzemin bir hale getirirken bir yandan da özellikle son göç dalgalarının gösterdiği gibi ulus devletlerin sınır duvarlarını alabildiğine yükseltmesine yol açıyor ve genel olarak bütün ayrımcılıkları körüklüyor çünkü muazzam bir eşitsizlikle işliyor. Bu kadar eşitsiz bir dünyada da insanlar daha çok kimliklerine sarılıyorlar çünkü ellerindeki odur ve kimlikleri onlara en azından bir tutamak sunuyor. Olmayan ekonomik-politik programların, olmayan gelecek ümitlerinin ikamesini sunuyor. Dolayısıyla tam tersine bütün kimliklerin patladığı bir döneme girildi. Sonuç olarak eşitsizliklerin derinleştiği bir dünyada, buna dair güçlü bir çözüm oluşturmadan, milliyetçilik ve genel olarak kimlik hareketlerini önlemek mümkün değil.

> Avrasyacılık fikrini biraz daha açar mısınız? Sizce bu düşünce siyasi olarak nereye tekabül ediyor?

Bence Avrasyacılık anti Batı merkezli bir söylem. Batı ile ilgili bir tehdit algısının dışa vurumu. Kendisi pozitif bir toplumsal siyasi tasarım olarak içi boş geliyor bana. İçini anca bir jeopolitik tasarımla, bir askeri strateji olarak kurgulayarak doldurmaya çalışanlar var. Zaten genellikle de askeri figürlerden oluşuyor bu kişiler. Ama mesela Alev Alatlı gibi, Türkiye’nin ruhunu daha çok Rus ruhuna benzeten, bizim Batılılardan çok Ruslara benzediğimizi söyleyerek derinleştirmeye çalışanlar var ama bu fikirlere gerçekten kulak veren var mı bilmiyorum. Avrasyacılık dediğiniz şey, tekrarlayayım, esas olarak anti-Batı hissiyatıın bir jeneratörüdür.

